#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
wmname LG3D &
# discord &
dunst &
# xrandr --output DisplayPort-0 --mode 1920x1080 --rate 144.01
$HOME/.xprofile
$HOME/.config/polybar/launch.sh
picom --experimental-backends
feh --bg-fill /home/$USER/.wallpapers/bosque.png
play /home/$USER/.sounds/startup.mp3

bspc monitor -d I II III IV V V1 VII VIII IX X

bspc config border_width         0
bspc config window_gap         	 8
bspc config border_radius        20.0

bspc config split_ratio          1
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# enable mouse for floating windows
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# purple color
bspc config focused_border_color \#8884FF

# old color #E95678
bspc config normal_border_color  \#EFC34B
bspc config presel_feedback_color \#EFC34B


xsetroot -cursor_name left_ptr

bspc rule -a * floating=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a discord state=floating center=true rectangle=1600x900+0+0
#bspc rule -a spotify state=floating center=true rectangle=1600x900+0+0
bspc rule -a Thunar state=floating center=true
bspc rule -a Slack state=floating center=true rectangle=952x732+0+0
bspc rule -a MeChat state=floating center=true
bspc rule -a Steam state=floating center=true
bspc rule -a minecraft-launcher state=floating center=true


bspc rule -a zoom state=floating
bspc rule -a notion-app state=floating center=true
bspc rule -a telegram-desktop state=floating center=true
bspc rule -a TelegramDesktop state=float center=true
bspc rule -a xfce4-terminal state=floating center=true
bspc rule -a alacritty state=floating center=true

xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true
